#ifndef MACEDIGIMESHWRAPPER_GLOBAL_H
#define MACEDIGIMESHWRAPPER_GLOBAL_H

#ifdef _MSC_VER
#if defined(MACEDIGIMESHWRAPPER_LIBRARY)
#  define DIGIMESHSHARED_EXPORT __declspec(dllexport)
#else
#  define DIGIMESHSHARED_EXPORT __declspec(dllimport)
#endif
#else
#  define DIGIMESHSHARED_EXPORT
#endif

#endif // MACEDIGIMESHWRAPPER_GLOBAL_H
